# Site settings
name: Data Tracer
title: The data tracer project aims at identifying metadata using machine learning
email: info@email.com
description: > # this means to ignore newlines until "baseurl:"
  The data tracer project aims at identifying metadata using machine learning. Where did the data come from, where did it go, what transforms happened, types, connections, are all what we aspire to identify.
baseurl: "/dtracer/" # the subpath of your site, e.g. /blog/
url: "https://dzinemon.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

# Build settings
markdown: kramdown

exclude:
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js
  - README.md
  - .jekyll-cache
  - bootstrap-vars.scss

keep_files:
  - _site/css
  - _site/js

include: ['_pages']